# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7jXzDTro-J85FWmHFFjAZcFvMEr3Sx9
"""

import pandas as pd

# Load the pipeF.csv file into a DataFrame
df = pd.read_csv('pipeF.csv')

# Strip any whitespace from column names
df.columns = df.columns.str.strip()

# Convert 'us', 'Alaska', and 'GOM' columns to numeric, handling commas and potential non-numeric values
df['us'] = pd.to_numeric(df['us'].str.replace(',', ''), errors='coerce')
df['Alaska'] = pd.to_numeric(df['Alaska'], errors='coerce')
df['GOM'] = pd.to_numeric(df['gom'].str.replace(',', ''), errors='coerce') # Assuming 'gom' is the correct column name based on kernel state

# Calculate 'L48 volume' by subtracting 'Alaska' and 'GOM' from 'us'
df['L48 volume'] = df['us'] - df['Alaska'] - df['GOM']

"""### Loading Data from EIA Excel File

Now, I will load the data from the provided URL into a new pandas DataFrame called `eia_df`. I'm assuming the data starts on 'Data 1' sheet and skips the first 2 rows, which is a common format for EIA's Excel files. If this doesn't look right, please let me know!
"""

eia_url = 'https://www.eia.gov/dnav/pet/xls/PET_CRD_CRPDN_ADC_MBBL_M.xls'

try:
    # Attempt to read the Excel file from the URL
    # Common sheet name is 'Data 1' and data usually starts after a few header rows (e.g., skip 2 rows)
    eia_df = pd.read_excel(eia_url, sheet_name='Data 1', skiprows=2)
    display(eia_df.head())
except Exception as e:
    print(f"Error loading data: {e}")
    print("Please check the URL, sheet name, or skiprows argument if the data doesn't load correctly.")

"""### Filtering Data Before 2010

Now, I'll convert the 'Date' column to datetime objects and then filter out all rows with dates before January 1, 2010.
"""

# Convert the 'Date' column to datetime objects
# The column name 'Date' from the eia_df.head() output seems correct.
# Using errors='coerce' to turn any unparseable dates into NaT (Not a Time).
eia_df['Date'] = pd.to_datetime(eia_df['Date'], errors='coerce')

# Filter out rows where 'Date' is before 2010
eia_df_filtered = eia_df[eia_df['Date'].dt.year >= 2010].copy()

# Display the head of the filtered DataFrame to confirm the change
display(eia_df_filtered.head())

"""### Converting Dates to Month-End

I will now adjust the 'Date' column in `eia_df_filtered` to represent the last day of each month. This is useful for consistent monthly aggregations or reporting.
"""

# Convert the 'Date' column to the last day of the month
eia_df_filtered['Date'] = eia_df_filtered['Date'].dt.to_period('M').dt.end_time

# Display the head of the modified DataFrame to confirm the change
display(eia_df_filtered.head())

"""### Dropping Time Component from Date Column

I will now convert the 'Date' column from datetime objects to just date objects, removing the time component.
"""

# Drop the time component from the 'Date' column
eia_df_filtered['Date'] = eia_df_filtered['Date'].dt.date

# Display the head of the modified DataFrame to confirm the change
display(eia_df_filtered.head())

# Display the first 5 rows with the new 'L48 volume' column
display(df.head())

# Convert 'Date' column to datetime objects
df['Date'] = pd.to_datetime(df['Date'])

# Set 'Date' as the index for resampling
df_indexed = df.set_index('Date')

# Resample to monthly frequency and calculate the mean for numeric columns
df_monthly_avg = df_indexed[['us', 'Alaska', 'GOM', 'L48 volume']].resample('M').mean().reset_index()

# Display the first few rows of the monthly average data
display(df_monthly_avg.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 8))

sns.lineplot(x='Date', y='us', data=df_monthly_avg, label='US Volume')
sns.lineplot(x='Date', y='Alaska', data=df_monthly_avg, label='Alaska Volume')
sns.lineplot(x='Date', y='GOM', data=df_monthly_avg, label='GOM Volume')
sns.lineplot(x='Date', y='L48 volume', data=df_monthly_avg, label='L48 Volume (US - Alaska - GOM)')

plt.title('Monthly Average Volumes Over Time')
plt.xlabel('Date')
plt.ylabel('Average Volume')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import plotly.express as px

fig = px.line(df_monthly_avg, x='Date', y=['us', 'Alaska', 'GOM', 'L48 volume'],
              labels={
                  'value': 'Average Volume',
                  'variable': 'Volume Type'
              },
              title='Monthly Average Volumes Over Time (Interactive)')

# Update legend names for clarity
fig.for_each_trace(lambda t: t.update(name = t.name.replace('us', 'US Volume').replace('Alaska', 'Alaska Volume').replace('GOM', 'GOM Volume').replace('L48 volume', 'L48 Volume (US - Alaska - GOM)')))

fig.show()



import plotly.express as px

# Map the column name to your desired color
color_map = {
    'GOM': 'blue',
    'us': '#1f77b4',          # Optional: explicitly set standard colors for others if needed
    'Alaska': '#ff7f0e',
    'L48 volume': '#2ca02c'
}

fig = px.line(
    df_monthly_avg,
    x='Date',
    y=['us', 'Alaska', 'GOM', 'L48 volume'],
    color_discrete_map=color_map,  # This changes GOM to blue
    labels={
        'value': 'Average Volume',
        'variable': 'Volume Type'
    },
    title='Monthly Average Volumes Over Time (Interactive)'
)

# Update legend names for clarity
fig.for_each_trace(lambda t: t.update(name = t.name.replace('us', 'US Volume').replace('Alaska', 'Alaska Volume').replace('GOM', 'GOM Volume').replace('L48 volume', 'L48 Volume (US - Alaska - GOM)')))

fig.show()